jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Docker with Compose
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app \
          docker/compose:latest sh -c "docker-compose run --rm app python manage.py test"

      - name: Run Linting in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app \
          docker/compose:latest sh -c "docker-compose run --rm app flake8"
